apiVersion: v1
kind: Service
metadata:
  name: data101-interactive
  labels:
    app.kubernetes.io/name: data101-interactive
spec:
  selector:
    app.kubernetes.io/name: data101-interactive
  ports:
    - name: http
      port: 80
      targetPort: http

